name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest pytest-mock pytest-cov requests-mock coveralls
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install pytest annotation plugin
      run: pip install pytest-github-actions-annotate-failures
        
    - name: Generate coverage report
      run: |
        pytest --cov=cblaster/ --cov-report=xml -vv

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
